{% set name = "lambdaprompt" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lambdaprompt-{{ version }}.tar.gz
  sha256: 672169432af843dfb46a28e50d59eeaa313df62ca6a0eab844cf891d91069275

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - requests
    - aiohttp
    - python-dotenv
    - jinja2
    - nest-asyncio
    - pyyaml
    - tenacity
    - pydantic

test:
  imports:
    - lambdaprompt
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A functional programming interface for building AI systems
  home: https://github.com/approximatelabs/lambdaprompt
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
